version: 2.1
orbs:
  go: circleci/go@1.3.1
jobs:
  build:
    docker:
      - image: circleci/node:12.10-browsers
    steps:
      - go/install

      - run:
          name: Install protoc
          command: |
            version=3.12.0
            archive=protoc-${version}-linux-x86_64.zip
            curl -O -L https://github.com/protocolbuffers/protobuf/releases/download/v${version}/${archive}
            sudo unzip -d '/usr/local' ${archive} 'bin/*' 'include/*'
            sudo chmod +x /usr/local/bin/protoc
            rm ${archive}

      - run:
          name: Install conformance-test-runner
          command: |
            archive=conformance-test-runner-3.12.3-linux-x86_64.zip
            curl -O -L http://pub.devserver2.de/protobuf/conformance-test-runner-3.12.3-linux-x86_64.zip
            unzip ${archive}
            sudo cp libprotobuf.so.23 /usr/lib/
            sudo cp conformance-test-runner /usr/bin/
            sudo chmod +x /usr/bin/conformance-test-runner
            rm libprotobuf.so.23
            rm conformance-test-runner
            rm ${archive}


      # check out the code in the project directory
      - checkout

      - run: make
